-- user1 Loo9샵

CREATE TABLE tbl_iolist(
SEQ	NUMBER		PRIMARY KEY,	
IO_DATE	VARCHAR2(10),			
IO_TIME	VARCHAR2(10),			
IO_INPUT	CHAR(10)	NOT NULL,		
IO_PNAME	nVARCHAR2(30),			
IO_PRICE	NUMBER,			
IO_QUAN	NUMBER,			
IO_TOTAL	NUMBER			

);

DROP TABLE tbl_iolist;

CREATE SEQUENCE seq_iolist
START WITH 1 INCREMENT BY 1;

commit;